# 1 "src/registerPushPop.S"
# 1 "<built-in>"
# 1 "<command-line>"
# 31 "<command-line>"
# 1 "/usr/riscv64-linux-gnu/include/stdc-predef.h" 1 3
# 32 "<command-line>" 2
# 1 "src/registerPushPop.S"
.global _ZN5Riscv16pushAllRegistersEv
.type _ZN5Riscv16pushAllRegistersEv, @function
.align 4

_ZN5Riscv16pushAllRegistersEv:
    addi sp, sp, -256
    .irp index, 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
    sd x\index, \index * 8(sp)
    .endr
    ret

.global _ZN5Riscv15popAllRegistersEv
.type _ZN5Riscv15popAllRegistersEv, @function
.align 4

_ZN5Riscv15popAllRegistersEv:
    .irp index, 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
    ld x\index, \index * 8(sp)
    .endr
    addi sp, sp, 256
    ret
